### ISSUE TITLE
Won't run if F95Checker standard is running

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#1]
Since the main page states it creates its own Appdata folder, I took it for granted it would be able to run alongside the standard version from WillyJL.
Sadly, that's not the case. If it uses it's own data folder then there shouldn't be an issue running it alongside.

**Comment by littleraisins** [comment]
Don't forget that each version is also running an RPC server.
I you really want them to run at the same time for some reason, I can change server port.

**Comment by FaceCrap** [comment]
> Don't forget that each version is also running an RPC server. I you really want them to run at the same time for some reason, I can change server port.

I suspected after writing it had something to do with the RPC part. Running them alongside each other isn't directly what I wanted, but just assumed possible. 
No real need for it, so leave the RPC port as is.
