### ISSUE TITLE
Crash while using `Previous` or `Next` buttons on Info popup

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#10]
I was adding additional images, and all seemed fine. I did it however by closing the info popup and clicking the next game in the list, ignoring the `Previous` and `Next` buttons next to the info popup.

Realizing that I was doing more than needed, I wanted to click on the `Next` button.

![image](https://github.com/littleraisins/F95CheckerX/assets/95778718/60e3ce38-6ec0-4ac4-be27-44725f04dfb3)

I did have a search filter active at the time. But even without an active search filter, it also crashes right after clicking the `Next` button.

Is repeatable. Only happens when clicking the `Previous`or `Next` buttons, not when closing the Info popup and just clicking the next game in the list.

Edited the issue title. Is not related to adding additional images, just plain using those buttons on the Info popup,

**Comment by littleraisins** [comment]
Fixed in build 46
