### ISSUE TITLE
Suggestion: Sort added list while adding/managing Tags for the Extension Feature (Positive/Negative/Critical)

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#11]
I noticed when you add tags for the new Extension feature, they get added in the order you add them. If you later add new ones or even while adding them the first time, they don't get sorted alphabetical if you add them out of alphabetical order.

Would be nice to have them sorted during the adding/managing process.

**Comment by littleraisins** [comment]
Fixed in build 46
