### ISSUE TITLE
Prefix filter queries get sent to F95Zone when hitting `Enter`

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#12]
I was creating a filter based on various developers using `dev:` and `OR` and accidentally pressed `Enter` after I completed it. 

It then got sent to F95Zone and my filter cleared... Now, this should happen when you're actually searching for a game, either by thread title or link. But not when you are creating a filter using prefixes as I don't think that will work 😉 

So may be an idea when using prefixes to prevent `Enter` from executing a query as a forum search...

**Comment by littleraisins** [comment]
Yeah, this is annoying.
Maybe changing `Enter` to `Ctrl+Enter` would be better?

**Comment by FaceCrap** [comment]
> Yeah, this is annoying. Maybe changing `Enter` to `Ctrl+Enter` would be better?

Not a bad idea, saves a lot of headaches adding code to detect if you are in filter mode or actually wanting to search on the forum, plus that combo is much less likely to be pressed by accident.

**Comment by littleraisins** [comment]
Search is now triggered by Crtl+Enter combo.
And items selected in autocomplete can now be applied by pressing Enter in addition to Tab and Right arrow.

**Comment by FaceCrap** [comment]
Cool 👍
