### ISSUE TITLE
Game cell resetting cycle image id when in kanban view

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#14]
I mentioned this in another issue, can't find back where, but don't think I got feedback on it.

When you have added additional images, it would be nice if these got shown in the `Refresh` button just like the banner image when you hover a game in either view (List/Grid/Kanban)

In Grid or Kanban view it would look even nicer if instead of showing them in the `Refresh` button, it would do so in the actual game cell instead, but that is just icing on the cake.

I know :grin: I just need to click to open the Info popup, and it's a great thing to have them even showing in almost full screen if you keep the mouse down on the banner image.  
Still, it's just one of those little things that makes it just that more fun to use.

**Comment by littleraisins** [comment]
It was implemented in the latest build.
Under "Images" section toggle "Cycle on hover"

**Comment by FaceCrap** [comment]
> It was implemented in the latest build. Under "Images" section toggle "Cycle on hover"

Damn you're fast 👍 didn't even realize.

**Comment by FaceCrap** [comment]
And the first issue. Actually... don't know if you can call it that...

In Kanban view, it can happen a game shows in more than one column. 
If you then hover that game, and it has additional images, the cell in the other column(s) and the refresh button start to show the first additional image, but...
Both the image in the Refresh button and the image in the other cell(s) immediately switch back to the banner image, while the banner image in the hovered cell stays static during all this.

**Comment by littleraisins** [comment]
Never used kanban view, so, i guess this is my excuse for not testing it properly this time :woozy_face:
