### ISSUE TITLE
Suggestion: Slightly change displayed Extension name and Context Menu item names

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#15]
Originally there was only the option to add either page or link to F95Checker, so the names
`Add page to F95Checker` and `Add link to F95Checker` were sensible.

Now we have more options and a context submenu. Which makes the current items look a bit superfluously wordy, I don't know how else to call it... it just feels off...

Personally, I changed it a bit, and thought perhaps it might be an idea to suggest and see what you think.

I changed the name in the manifest to just `F95CheckerX Addon` since it's obvious we're using it in a browser, so I just dropped that part as it doesn't need to be pointed out. 
I also changed the main Context Menu item to `F95CheckerX Addon`, again we're using a browser, so it doesn't need to be mentioned here either.
I would even replace the word `Addon` with something else if I could come up with a better alternative, since it's fairly obvious it's an addon already.

And canged the Context Submenu items to:

`Add page to Game list`  
`Add link to Game list`
`Add page to Reminders`
`Add link to Reminders`

A) Removed the repeated F95CheckerX, since it's obvious from the parent menu where they go, but instead explicitly named the target part of F95CheckerX, namely either the Game list or the Reminders.
B) removed `this` since it is fairly obvious you aren't adding other pages or other links and that shouldn't need to be pointed out again.

Again, this is just me being OCD'ishly nitpicky, do with it what you will.

**Comment by littleraisins** [comment]
Fixed in build 46.
I've decided to completely get rid of the `Browser Addon` suffix and keep `F95CheckerX` as the extension name.
Everything else was changed based on your suggestions.
