### ISSUE TITLE
RPDL query character replacements

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#16]
I don't know if you read it, but I posted this before on @Willy-JL's [issue list](https://github.com/Willy-JL/F95Checker/issues/91).

In the past, rpdl.net dropped non-alphabetic characters from torrent names just like F95Checker does and consequently F95CheckerX too.
But some time ago, the RPDL team started converting `&` characters to their alphabetical `and` representation in torrent names. 
I haven't seen them using this for other non-alphabetical characters yet, but this one happens to be dealt with different these days.

This causes searches for torrents like for [The Shrink R&R](https://f95zone.to/threads/the-shrink-r-r-v1-9-onemanvn.36610/) to become `TheShrinkRR` which doesn't produce a result.
Like I suggested in the F95Checker repo, it would be nice if the program also changed `&` to `and`, for the same reason I mentioned there.
It's not a big deal if you're aware of it, and there is of course the search box to change the query, but there's always going to be that one dimwit that doesn't realize and calls it a bug.

**Comment by littleraisins** [comment]
Do you have any more examples of such special character replacements?

**Comment by littleraisins** [comment]
Implemented handling of `&` in build 49.
If you find more examples, post them here.
