### ISSUE TITLE
Method to show cycling images in a random order

### ISSUE THREAD

**Issue by Valter4** [littleraisins/F95CheckerX#19]
Or something alike.
Merely a suggestion, but this would be Very Cool

If a method this direct is not feasible, an option to make it so the cycling continues where it left off after the user stopped hovering over the game would also be nice.
I'm aware that this system is setup so that the image chosen as "banner" is always the first. I don't expect that one to be able to be randomized nor does it matter much.

I appreciate your work thus far. Cycling multiple images is already a great addition to this software.

**Comment by littleraisins** [comment]
Implemented in build 56
Check it out, if everything works as expected, you can close the issue
