### ISSUE TITLE
Invert filter selection

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#2]
Doesn't seem to be a way to invert the selected filter, i.e. to show everything _except_ the selected filter.

**Comment by littleraisins** [comment]
I'm pretty sure creating negative filter should work.
For example, if you want to exclude unity games you can type `-type:unity`

Did you find filtering help window(pressing F1 in the search field)? Maybe i need to make it more obvious how to get there.

**Comment by FaceCrap** [comment]
> I'm pretty sure creating negative filter should work. For example, if you want to exclude unity games you can type `-type:unity`
> 
> Did you find filtering help window(pressing F1 in the search field)? Maybe i need to make it more obvious how to get there.
To be honest, I did see the text, just completely didn't think to actually press F1.

My bad, I tried any combination and placement of ! and `not` I could think of... but just failed to press F1
