### ISSUE TITLE
`Manage extension tags` still uses `ntr` tag as display form. Forum however uses `netorare` as display form. This causes mismatch in highlighting

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#20]
The `Manage extension tags` dropdown still has the `ntr` tag. The forum however doesn't use it anymore in textual form, the only tag I could see in the filter list on the forum is `netorare` .
The tag list still has it as `ntr` I guess when looking at the `href`, but the display name is changed. As a result, it doesn't get highlighted if you add `ntr` to either positive or negative list.

I see in the DB you add them by name into the settings table... I'm guessing easier for the extension?  Seeing as this does a match by name.
Luckily this made it easier to rename `ntr` to `netorare` in the settings field and that solves the issue.

**Comment by littleraisins** [comment]
Fixed in build 56
