### ISSUE TITLE
Point & Click tag not recognized

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#22]
Got another one where the displayed form of the tag differs from the actual tag used.

The `Point & Click` tag is the displayed form, but the forum itself uses `href="/tags/point-click"` underwater.

**Comment by littleraisins** [comment]
It was intended this way
`Tag` struct [uses href form](https://github.com/littleraisins/F95CheckerX/blob/999e52276e88d7b74c890cc4ec79add95030893e/modules/structs.py#L313) to save tags in database.
`CLEAR_TAGS` variable is [used for tag highlighter](https://github.com/littleraisins/F95CheckerX/blob/999e52276e88d7b74c890cc4ec79add95030893e/modules/structs.py#L456).
You have probably reported this because `point & click` tag is not highlighted, and I have no idea why.
I'll probably revert back to using `href`s for tag highlighter in the next build.

**Comment by FaceCrap** [comment]
The thing is, your highlighter uses the visual representation... 
`Point & Click` might get ignored because of the & which could be because that is normally used to indicate a hotkey character, so might need escaping... 

There's two more that have a display form different from the `href`.
visual `female domination` -> href = `femaledomination`
visual `male domination` - href -> `maledomination`
I added a testblock to the extension for the tagcloud page... and those are the only three not getting recognized.

![image](https://github.com/littleraisins/F95CheckerX/assets/95778718/0d2d8d71-c15e-4109-9e95-d85ad9f8cf9e)

**Comment by FaceCrap** [comment]
> Tbh, I don't know why I decided to use names instead of hrefs in the first place, it was a stupid idea.

The display form is the only thing you can easily use in the extension itself... doubt you want the extension (and thus a F95Zone page, accessing the db to get the href version)

**Comment by FaceCrap** [comment]
To make it foolproof... extend the extension test to include both the href and the display form?

**Comment by FaceCrap** [comment]
Duh... testing against .innerText besides innerHTML solves the `Point & Click` but doesn't do anything for the `(fe)male domination` tags...

**Comment by FaceCrap** [comment]
Ok, `point & click` fixed, see previous post. the other two I can't fix because their is a space in the display form, and the two in the list in the checker don't.

**Comment by FaceCrap** [comment]
Stumped... 
Thought to just do the quick&dirty by testing for the occurence of `male dom` in whatever `for each` ... `const name`  gets stored.

Not doing anything....

Since I can't debug extensions I made a small testscript in ViolentMonkey

```javascript
// ==UserScript==
// @name        New script - f95zone.to
// @namespace   Violentmonkey Scripts
// @match       https://f95zone.to/tags/
// @grant       none, 
// @version     1.0
// @author      -
// @description 10/4/2023, 8:06:19 PM
// ==/UserScript==
const tagCloud = document.querySelectorAll('a.tagCloud-tag');
tagCloud.forEach((tag) => {
    if (tag.textContent.endsWith(' domination')) {
        var name = tag.textContent;
        name.replace('male dom','maledom');
    }
});```

And I'm stumped... with a breakpoint on `var name` it halts for both tags... but changing it in the next statement. I wish... not happening. Tried it three ways from sunday... directly in `tag.textContent`, `tag.innerHTML`, `tag.innerText`, you name it, none of the properties that point to the text content so much as blinks... it.just.don't.change
