### ISSUE TITLE
The game "College Bound" doesn't get parsed properly

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#25]
Not sure whether this is something caused by the tread's formatting or a bug in the code. This actually a problem that also exists in WillyJL's F95Checker 
Whatever the cause, the game ["College Bound"](https://f95zone.to/threads/70256/) doesn't get parsed properly.

The description tab shows a part of the changelog, starting with the word `part` and some text, and the remainder shows whatever changed in v0.4.1.3 and before.
It ends where the changelog containes the first spoiler in the entry for v0.3.0, including the spoiler itself 

I suspect it is the word `Story` breaking the parsing, as the entry for v0.4.1.4 has a `ul` where the second `li` starts with the text `Story part` in bold. And it's right in the middle of this string the description tab starts.

Oddly enough, the changelog tab itself has the full changelog.

Probably as a result, the download tab is also completely empty.

**Comment by littleraisins** [comment]
Unfortunately, there is no good way to fix this without breaking parsing of other threads.

**Comment by FaceCrap** [comment]
Does that also include the downloads section not getting populated? 
The description not getting picked up is, although a minor annoyance, something I can live with.
However, the downloads not being picked up is a bigger problem since that forces you to still visit the thread for the extra's.
