### ISSUE TITLE
Managed Images popup space usage

### ISSUE THREAD

**Issue by FaceCrap** [littleraisins/F95CheckerX#6]
Seeing as screenshots usually have the same ratio and the popup can't be resized, maybe an idea to use all available space instead of just the one column, leaving a lot of black?
Maybe even reduce the height a bit and make it three columns?

NOTE: Image is scaled down, click for full size.
<img src="https://github.com/littleraisins/F95CheckerX/assets/95778718/6b7c7528-e0ac-4742-b6ad-d4eac248770e"  height=300px style="object-fit:contain" />

**Comment by littleraisins** [comment]
Yeah, I really dislike it too.
Initially, it looked just like you described, with multiple columns, filling all available space. 
However, due to some quirks of immediate mode GUIs, heavy flickering occurred.

The only viable solution I can think of right now is to fit every image to a 16:9 ratio and make it a grid.

**Comment by FaceCrap** [comment]
> due to some quirks of immediate mode GUIs, heavy flickering occurred when dragging.
What do you mean with dragging? I am encountering a bit of an issue atm with image cycling, so had to empty the column in the db where the  urls get stored and remove all non-banner images.

So I haven't even tried of those could be dragged... but if that's an issue, then don't allow dragging? 
If you mean dragging images from Explorer, I noticed if the file explorer popup remains open after dragging the first image, you can just drag and drop each next image and it'll get added.
Dropping all images for one game in one go don't work, but didn't actually expect it.

As far as fitting to 16:9, for the few games I tried, it looked like each image already was in a fixed size box?

**Comment by littleraisins** [comment]
> Please don't close an issue until the issue is actually fully resolved

Sure, my bad

By dragging I mean rearranging images in the list.
I've fixed the aspect ratio in the latest build, it should look like a grid now.

**Comment by FaceCrap** [comment]
> > Please don't close an issue until the issue is actually fully resolved
> 
> Sure, my bad
> 

Thanks, I know it's relatively easy to switch to closed issues if there's a need for followup, but sometimes it's easier to leave it open a bit longer. Like I suspect also in this case.

> By dragging I mean rearranging images in the list. I've fixed the aspect ratio in the latest build, it should look like a grid now.
Why would you even allow or support that? 
If folks want to have custom images in a specific order, just tell them to add them in that order. 
And if adding automatically from the thread, folks just need to accept these show in the order as they appear in the thread.

Don't make it harder on yourself :wink:

I just saw the update notification, also noticed the double period was already fixed,  

During all those image refreshes I came across two threads where the image couldn't be loaded and produced an "Invalid format" message.

This also happens in WillyJL's version. And I'm fairly sure it's caused by an embedded thumbnail.  
These are the threads: [Naughty Lyanna](https://f95zone.to/threads/30364/) and [Maou-Sama](https://f95zone.to/threads/47559/)

These two banners, when downloaded and viewed in XnView, are 32bit (instead of regular 24bit since no transparency present) and have an `Extra` field with binary junk (I suspect an embedded thumbnail). 
I somehow got rid if it by converting them to lossles webm and back to png.  
Since your version also can't deal with these two banners, maybe you can figure a way to strip this field, or find a way around the issue without the need to strip it.
Read you would forward things to WillyJL if it also affects the regular version.

Now, this issue with those two banner issues is not directly related to the cycle image popup. But, seeing as I did experience some trouble when I played with this feature, 
I suspect there might be some thread images having the same `extra` field as the banner images in the above threads. The two threads mentioned at least have clean thread images.

**Comment by littleraisins** [comment]
> Folks just need to accept these show in the order as they appear in the thread.

That's the catch since downloading happens asynchronously, images will most likely be saved in random order, different from how it is in the thread. 

> Don't make it harder on yourself

One of the reasons I picked up this project is to familiarize myself with the immediate mode paradigm. It was a good exercise and actually a very useful feature I really wanted to have.

> image couldn't be loaded and produced an "Invalid format" message.

Yeah, image helper (imagehelper.py) is fairly limited at the moment. I'll see what I can do.
Opened issue #8 to track this.

**Comment by FaceCrap** [comment]
Oooh 😄 I actually like what you did with the cycled images, the grid is even configurable. The speed with which the popup grows could be a tad faster, but it's not annoyingly slow.
Suggestion though. The icons on the far right, they are both the same and have a very tiny character next to it. The one that enlarges the images looks like a `x` and the one that reduces the images looks like a `+`.
It's hard to tell on my monitor if it's a `+` or a division symbol. 

Either way, the icons don't really represent their function and the little symbols are a bit confusing... `+` to zoom out? 

I tried looking through the font-awesome icon list in a Notes field for suitable replacements, but oddly enough, there's no zoom icons in that list
These are the ones I found which could be used as alternatives, some better than others.

`grid-large` and `grid` to indicate enlarging or reducing grid size. But maybe not so familiar for most folks.
`arrow-expand` and `arrow-collapse` would maybe fit even better, as these actually are probably more familiar with most folks to switch between larger and smaller video view size.
 `plus-circle-outline` and `minus-circle-outline`, although these might get confused with adding or removing images. OTOH, these seem to get used as zoom indicators too in some apps
 
The simplest might even be just the word `ZOOM` with a plus sign and minus sign on either side.

At any rate, better suited icons would remove the need for those tiny character thingies next to it.  

I suspect you will get complaints about these anyway, since there will be folks with bad eyesight who won't even be able to recognize these.

**Comment by littleraisins** [comment]
> The speed with which the popup grows could be a tad faster, but it's not annoyingly slow.

I'm not sure if I understand what you mean by that. Are you referring to the speed with which images load?

> I tried looking through the font-awesome icon list in a Notes field

The icon font used is not Font Awesome but Material Design Icons by Google, I use this handy [online reference](https://pictogrammers.com/library/mdi/) to find icons.
Icons used right now are [table-column-plus-after](https://pictogrammers.com/library/mdi/icon/table-column-plus-after/) and [table-column-remove](https://pictogrammers.com/library/mdi/icon/table-column-remove/).
Names and semantics make sense, but I agree they look cluttered and they are too small.

**Comment by FaceCrap** [comment]
> > The speed with which the popup grows could be a tad faster, but it's not annoyingly slow.
> 
> I'm not sure if I understand what you mean by that. Are you referring to the speed with which images load?

No, the images load blazingly fast, when you don't have cycle images yet, the popup opens and grows wider. 
Once you have added cycle images, the popup itself starts relatively small, and then the 'window' grows until it has reached the final size. 
It's this 'growing' that could be a tad faster.


> 
> > I tried looking through the font-awesome icon list in a Notes field
> 
> The icon font used is not Font Awesome but Material Design Icons by Google, I use this handy [online reference](https://pictogrammers.com/library/mdi/) to find icons. 
> Icons used right now are [table-column-plus-after](https://pictogrammers.com/library/mdi/icon/table-column-plus-after/) and [table-column-remove](https://pictogrammers.com/library/mdi/icon/table-column-remove/). 
> Names and semantics make sense, but I agree they look cluttered and they are too small.

Huh, ok the names may make sense, but the actual display doesn't 

![image](https://github.com/littleraisins/F95CheckerX/assets/95778718/998c023c-b583-47b7-a1de-5ab97931ebe9)

The left one with the `X` next to it makes the images larger, so effectively reducing the number of horizontal cells. 
The right one with the `+` (it _is_ a plus sign right?) makes the images smaller, effectively enlarging the number of horizontal cells.

So, it may be semantically correct, visually it will be seen as the exact opposite since folks will associate this with the image sizes and not with the number of cells in a row...

**Comment by FaceCrap** [comment]
Ok, I now see what `Fit` does, It makes images in the popup fit the cell if there are some images smaller than others.

**Comment by littleraisins** [comment]
Popup is fixed size and should resize instantly.
This growing behaviour shouldn't be happening and I suspect it's because you have increased interface scaling.
Am I right? I should have accounted for that, still figuring out immediate mode things.
Anyway, I'll fix that in the next build.

Will this work?
![image](https://github.com/littleraisins/F95CheckerX/assets/134188774/49ae105a-8412-4993-992b-22f687469b93)

**Comment by FaceCrap** [comment]
> Popup is fixed size and should resize instantly.
> This growing behaviour shouldn't be happening and I suspect it's because you have increased interface scaling. 
> Am I right? I should have accounted for that, still figuring out immediate mode things. Anyway, I'll fix that in the next build.

You are absolutely right, my interface is scaled 1.12x, and indeed, if I set it to 1.0x the popup shows instantly AND it has a more reasonable size 😁 

> Will this work? ![image](https://user-images.githubusercontent.com/134188774/269395546-49ae105a-8412-4993-992b-22f687469b93.png)

Perfect!

**Comment by FaceCrap** [comment]
This is how it looks with 1.12x scale
<img src="https://github.com/littleraisins/F95CheckerX/assets/95778718/99aa0d79-c4dc-43e8-9575-3cc0102a4416" width=300 style="object-fit: contain" />

This is how it is supposed to look then
<img src="https://github.com/littleraisins/F95CheckerX/assets/95778718/6a646ab3-1721-4350-9cd4-54b59f7e5739" width=300 style="object-fit: contain" />

I've been used to having it slightly scaled for so long I didn't realize, the whole UI is also actually a bit snappier at scale 1.0x

**Comment by FaceCrap** [comment]
Not sure if this is feasible. But would you consider cycling images in the refresh window when hovering a game for which you have added additional images?

**Comment by littleraisins** [comment]
> But would you consider cycling images in the refresh button
I already have this in my todo list 😃
