### ISSUE TITLE
Allow ImageHelper to load truncated images

### ISSUE THREAD

**Issue by littleraisins** [littleraisins/F95CheckerX#8]
Initially described [here](https://github.com/littleraisins/F95CheckerX/issues/6#issuecomment-1728124352)

**Comment by FaceCrap** [comment]
another thread to test it on. [Avalon](https://f95zone.to/threads/avalon-v8-2-lockheart.44397/) also throws an `invalid banner` message in the in the info popup and grid/kanban views.

**Comment by littleraisins** [comment]
Fixed in build 38.
I'll keep this issue open for a while, in case more similar issues arise.

**Comment by FaceCrap** [comment]
Seems to be fixed. Those three I encountered, I first actually physically deleted them and reset them in F95CheckerX, and this time the images got downloaded just fine.
